server:
  port: 80

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://81.71.120.235:18263/clothing_inventory?serverTimezone=UTC
    username: root
    password: 123456

  #  关闭spring Boot 的logo
  main:
    banner-mode: off
  mvc:
    view:
      prefix: /
      suffix: .html
#      禁用缓存的参数
  thymeleaf:
    cache: false
#    static-path-pattern: /static/**

mybatis-plus:
  #  关闭spring mybatis 的logo
  global-config:
    banner: false
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl